//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsGoBikingSelfHosted.GenericProxyCache {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JCDecauxItem", Namespace="http://schemas.datacontract.org/2004/07/GenericProxyCache")]
    [System.SerializableAttribute()]
    public partial class JCDecauxItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string queryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                if ((object.ReferenceEquals(this.queryField, value) != true)) {
                    this.queryField = value;
                    this.RaisePropertyChanged("query");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenericProxyCache.IProxyCache")]
    public interface IProxyCache {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/getContractsList", ReplyAction="http://tempuri.org/IProxyCache/getContractsListResponse")]
        LetsGoBikingSelfHosted.GenericProxyCache.getContractsListResponse getContractsList(LetsGoBikingSelfHosted.GenericProxyCache.getContractsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/getContractsList", ReplyAction="http://tempuri.org/IProxyCache/getContractsListResponse")]
        System.Threading.Tasks.Task<LetsGoBikingSelfHosted.GenericProxyCache.getContractsListResponse> getContractsListAsync(LetsGoBikingSelfHosted.GenericProxyCache.getContractsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/getStationsList", ReplyAction="http://tempuri.org/IProxyCache/getStationsListResponse")]
        LetsGoBikingSelfHosted.GenericProxyCache.getStationsListResponse getStationsList(LetsGoBikingSelfHosted.GenericProxyCache.getStationsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/getStationsList", ReplyAction="http://tempuri.org/IProxyCache/getStationsListResponse")]
        System.Threading.Tasks.Task<LetsGoBikingSelfHosted.GenericProxyCache.getStationsListResponse> getStationsListAsync(LetsGoBikingSelfHosted.GenericProxyCache.getStationsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/getStationsListWithContractName", ReplyAction="http://tempuri.org/IProxyCache/getStationsListWithContractNameResponse")]
        LetsGoBikingSelfHosted.GenericProxyCache.getStationsListWithContractNameResponse getStationsListWithContractName(LetsGoBikingSelfHosted.GenericProxyCache.getStationsListWithContractNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/getStationsListWithContractName", ReplyAction="http://tempuri.org/IProxyCache/getStationsListWithContractNameResponse")]
        System.Threading.Tasks.Task<LetsGoBikingSelfHosted.GenericProxyCache.getStationsListWithContractNameResponse> getStationsListWithContractNameAsync(LetsGoBikingSelfHosted.GenericProxyCache.getStationsListWithContractNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContractsList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getContractsListRequest {
        
        public getContractsListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContractsListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getContractsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public LetsGoBikingSelfHosted.GenericProxyCache.JCDecauxItem getContractsListResult;
        
        public getContractsListResponse() {
        }
        
        public getContractsListResponse(LetsGoBikingSelfHosted.GenericProxyCache.JCDecauxItem getContractsListResult) {
            this.getContractsListResult = getContractsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationsList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStationsListRequest {
        
        public getStationsListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationsListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStationsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public LetsGoBikingSelfHosted.GenericProxyCache.JCDecauxItem getStationsListResult;
        
        public getStationsListResponse() {
        }
        
        public getStationsListResponse(LetsGoBikingSelfHosted.GenericProxyCache.JCDecauxItem getStationsListResult) {
            this.getStationsListResult = getStationsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationsListWithContractName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStationsListWithContractNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string contractName;
        
        public getStationsListWithContractNameRequest() {
        }
        
        public getStationsListWithContractNameRequest(string contractName) {
            this.contractName = contractName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationsListWithContractNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStationsListWithContractNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public LetsGoBikingSelfHosted.GenericProxyCache.JCDecauxItem getStationsListWithContractNameResult;
        
        public getStationsListWithContractNameResponse() {
        }
        
        public getStationsListWithContractNameResponse(LetsGoBikingSelfHosted.GenericProxyCache.JCDecauxItem getStationsListWithContractNameResult) {
            this.getStationsListWithContractNameResult = getStationsListWithContractNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyCacheChannel : LetsGoBikingSelfHosted.GenericProxyCache.IProxyCache, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyCacheClient : System.ServiceModel.ClientBase<LetsGoBikingSelfHosted.GenericProxyCache.IProxyCache>, LetsGoBikingSelfHosted.GenericProxyCache.IProxyCache {
        
        public ProxyCacheClient() {
        }
        
        public ProxyCacheClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyCacheClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LetsGoBikingSelfHosted.GenericProxyCache.getContractsListResponse getContractsList(LetsGoBikingSelfHosted.GenericProxyCache.getContractsListRequest request) {
            return base.Channel.getContractsList(request);
        }
        
        public System.Threading.Tasks.Task<LetsGoBikingSelfHosted.GenericProxyCache.getContractsListResponse> getContractsListAsync(LetsGoBikingSelfHosted.GenericProxyCache.getContractsListRequest request) {
            return base.Channel.getContractsListAsync(request);
        }
        
        public LetsGoBikingSelfHosted.GenericProxyCache.getStationsListResponse getStationsList(LetsGoBikingSelfHosted.GenericProxyCache.getStationsListRequest request) {
            return base.Channel.getStationsList(request);
        }
        
        public System.Threading.Tasks.Task<LetsGoBikingSelfHosted.GenericProxyCache.getStationsListResponse> getStationsListAsync(LetsGoBikingSelfHosted.GenericProxyCache.getStationsListRequest request) {
            return base.Channel.getStationsListAsync(request);
        }
        
        public LetsGoBikingSelfHosted.GenericProxyCache.getStationsListWithContractNameResponse getStationsListWithContractName(LetsGoBikingSelfHosted.GenericProxyCache.getStationsListWithContractNameRequest request) {
            return base.Channel.getStationsListWithContractName(request);
        }
        
        public System.Threading.Tasks.Task<LetsGoBikingSelfHosted.GenericProxyCache.getStationsListWithContractNameResponse> getStationsListWithContractNameAsync(LetsGoBikingSelfHosted.GenericProxyCache.getStationsListWithContractNameRequest request) {
            return base.Channel.getStationsListWithContractNameAsync(request);
        }
    }
}
